apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.fullname }}
  labels:
    app: {{ .Values.app.fullname }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.org/client-max-body-size: 10m
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication required to access this site'
spec:
  tls:
    - hosts:
      - progimage.innovology.io
      secretName: progimage-tls
  rules:
    - host: progimage.innovology.io
      http:
        paths:
          - path: /upload
            backend:
              serviceName: {{ .Values.upload.fullname }}
              servicePort: http
          - path: /images
            backend:
              serviceName: {{ .Values.download.fullname }}
              servicePort: http
