kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.fullname }}
  labels:
    app: {{ .Values.app.fullname }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  storageClassName: "ssd"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv-one
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.progimageone.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: images
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
