apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.fullname }}
  labels:
    app: {{ .Values.redis.fullname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redistcp
      port: 6379
  selector:
    app: {{ .Values.redis.fullname }}
